__all__ = ['sportstream365',
           'mycujoo',
           'aliez',
           'assia',
           'livestream',
           'sportvisions',
           'flashstreams',
           'socolive',
           'sporcanli',
           'streamhd247',
           'sport7',
           '1me',
           '0eb',
           'sawlive']